module.exports = {
    EDIT_SUCCESS: 'Cập nhập thành công!',
    ADD_SUCCESS: 'thêm mới thành công!',
    STATUS_SUCCESS: 'Cập nhập status thành công!',
    GROUPS_ACP_SUCCESS: 'Cập nhập groups_acp thành công!',
    SPECIAL_SUCCESS: 'Cập nhập special thành công!',
    STATUS_MULTI_SUCCESS: 'Cập nhập %d status thành công!',
    DELETE_SUCCESS: 'Xóa thành công!', 
    ORDERING_SUCCESS:'Thay đổi ordering thành công!',
    DELETE_MULTI_SUCCESS: 'Xóa %d phần tử thành công!', 
    ERROR_NAME: 'chiều dài từ %d đến %d kí tự',
    ERROR_ORDERING: 'Phải là số nguyên lớn hơn %d và bé hơn %d',
    ERROR_STATUS: 'Status phải khác rỗng',
    ERROR_GROUPS_ACP: 'Groups_acp phải khác rỗng',
    ERROR_SPECIAL: 'Special phải khác rỗng',
    ERROR_GROUPS: 'Groups phải khác rỗng',
    ERROR_UPLOADS_AVATAR: 'vui lòng chọn avatar',
    ERROR_UPLOADS_THUMB: 'vui lòng chọn thumb',
    ERROR_LIMIT: 'Kích thước file không phù hợp',
    ERROR_CATEGORY: 'Category phải khác rỗng',
    ERROR_EMAIL: 'chiều dài email từ %d đến %d kí tự',
    ERROR_PASSWORD: 'chiều dài mật khẩu từ %d đến %d kí tự',
    ERROR_LOGIN_USERNAME_NOTEXIST: 'Username không tồn tại',
    ERROR_LOGIN_PASSWORD_INCORRECT: 'Mật khẩu không chính xác',
    ERROR_LOGIN: 'Thông tin đăng nhập không chính xác',
    ERROR_NAMESHAKE: 'Tên đã tồn tại',
    SUCCESS_CONTACT: 'Gửi thông tin liên hệ thành công',
    ERROR_NAMESHAKE: 'Name đã tồn tại'
}